services:
  - type: web
    name: go-ecom-backend
    env: go
    plan: free
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecom-db
          property: connectionString

